apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-generator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-generator
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "list", "delete", "deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-generator
subjects:
  - kind: ServiceAccount
    name: event-generator
    namespace: default
roleRef:
  kind: ClusterRole
  name: event-generator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: event-generator
  namespace: default
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: event-generator
    spec:
      serviceAccountName: event-generator
      restartPolicy: Never
      containers:
        - name: event-generator
          image: ghcr.io/tom-ludwig/otel-k8s-events-evaluation:0.0.2
          args:
            - "--target-rate=20"
            - "--warning-ratio=0.2"
            - "--duration=5m"
            - "--namespace=default"
            - "--workers=5"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
